### ISSUE TITLE
Re-Provision Device (Expired Cert)

### ISSUE THREAD

**Issue by dtischler** [ARMmbed/meta-mbl#718] opened 2019-09-22 02:44 UTC
### Description

Sorry for what is probably a novice question, I have read over the documentation, and am probably missing something rather simple...

Several months ago, I followed the instructions here to provision a few devices:  https://os.mbed.com/docs/mbed-linux-os/v0.8/first-image/provisioning-your-device.html

Which basically consists of: 
manifest-tool init -q -d <domain> -m <device class>
mbl-cli save-api-key <api-key>
mbl-cli provision-pelion  <cert-name> <update-cert-name> -c -p <update-cert-path>

I then shipped the devices to the field, kept one with me, and they have been online since that time.  However, today I attempted to add a new container to the devices with the "manifest-tool update device" command, and they simply hung and remained in a "Pending" status for a few hours before I gave up and killed the campaign.  Attempting to duplicate this on my local device I kept here, I was able to see in the logs that the Cert that was created at the time of provisioning is now expired, as it was only valid for 90 days.  (I then learned about the '-V' flag that could have been used at the time of provisioning for validity, but I simply followed the documentation as-is).

I believe the process to re-provision would simply be to re-run "mbl-cli provision-pelion", but, the device is no longer on my network (or accessible via the '-a' flag as it's not a public address it has).  If it were the 'manifest-tool' used for this process, I could simply use the '-device-id' flag, but, that does not seem to be available in the "mbl-cli" utility.

Thus, my simple question is, how can I now update the certificate that was originally provisioned to the Pi?  (Or push containers to the device if the expired cert is not actually the issue at play here.)

As a product feedback point, there is no indication of the expired cert issue in the web interface, and a campaign seems to hang indefinitely.  Using the command line to push via "manifest-tool update device" will hang indefinitely as well.  It was only via SSH to my local Pi and tailing the logs that I was able to discover this.

Thanks for all the assistance as always!

### Issue request type

    [X] Question
    [X] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment] 2019-09-22 05:49
*Internal Jira reference: https://jira.arm.com/browse/MBLTRIAGE-33*

**Comment by jjohnson-arm** [comment] 2019-09-24 13:20
You are correct that the problem is to do with the update certificate on the devices.

The documentation you followed is aimed at developers and not for production, as Mbed Linux OS is still in developer preview. We are sorry that we did not make it clear that the certificates produced would only last for 90 days (by default). We have a documentation change in progress to rectify this.

For production usage it is expected you create a certificate that is valid for at least 10 years. More information on this can be found in the following links:
* [factory provisioning process](https://www.pelion.com/docs/device-management/current/provisioning-process/factory-provisioning-process.html) - how production can be done in future
* [manifest tool usage](https://www.pelion.com/docs/device-management/current/updating-firmware/manifest-tool.html) - how another certificate authority can be inserted for instance

As part of the documentation change we are fixing the usage information about the manifest tool and dropping the incorrect usage of `-q` option to make it more obvious on what certificate is created - as it will ask how long the certificate should be valid for:
```
manifest-tool init -d <domain> -m <device class>
```

As you have identified, once an update certificate is on a device, it is not easy to replace. The only method would be to perform the re-provisioning with a new certificate. And the only way to do this is to connect to the device via a network connection, as there is no method to perform this update via the cloud. 

For the Pelion website issue - where the certificate expiry is not shown - please can you raise an issue on the portal - https://portal.mbedcloud.com/contact.

**Comment by dtischler** [comment] 2019-09-26 23:55
Thank you Jeremy for the detailed analysis and verifying that while this situation is not ideal, it is the expected behavior based on my provisioning steps.  So, I will figure some way to recover the devices as best I can.  

I suppose an additional (now obvious) piece of product feedback would thus be the creation / implementation of the ability to update that provisioning cert via the Web interface, or, using the manifest-tool, which simply allows for "manifest-tool update --device-id xxxx" without the need to be on the same network.

Thanks again for clarifying this issue though, I appreciate it greatly.

**Comment by ciarmcom** [comment] 2019-10-31 21:37
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment] 2019-11-01 16:48
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by dtischler** [comment] 2019-11-01 16:51
Thanks @adbridge !

**Closed** 2020-04-22 09:31 UTC
Labels: Jira status: REOPENED, mirrored
